fork = false
frame = "full"
idle = true
maximized = false
no-multigrid = false
srgb = false
tabs = true
theme = "auto"
title-hidden = true
vsync = false
wsl = false

[font]
normal = ["FantasqueSansM Nerd Font Mono"]
bold = ["FantasqueSansM Nerd Font Mono"]
italic = ["FantasqueSansM Nerd Font Mono"]
bold_italic = ["FantasqueSansM Nerd Font Mono"]
size = 16.0

