# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #C6BDD4
background         #121116
cursor             #C6BDD4

active_tab_foreground     #121116
active_tab_background     #C6BDD4
inactive_tab_foreground   #C6BDD4
inactive_tab_background   #121116

active_border_color   #C6BDD4
inactive_border_color #121116
bell_border_color     #171127

color0      #3A393E
color1		#171127
color2		#201833
color3		#291E3F
color4		#32254B
color5		#3B2C56
color6		#443262
color7		#A498B8
color8		#736B81
color9		#1F1735
color10		#2B2044
color11		#372854
color12		#433164
color13		#4F3A73
color14		#5B4383
color15		#A498B8
