# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #F6E4E4
background         #232326
cursor             #F6E4E4

active_tab_foreground     #232326
active_tab_background     #F6E4E4
inactive_tab_foreground   #F6E4E4
inactive_tab_background   #232326

active_border_color   #F6E4E4
inactive_border_color #232326
bell_border_color     #23202B

color0      #49494D
color1		#23202B
color2		#424453
color3		#5A484F
color4		#746B7C
color5		#886A6D
color6		#AD8585
color7		#EAD0D0
color8		#A49191
color9		#2E2B3A
color10		#585B6F
color11		#78616A
color12		#9B8EA5
color13		#B58D91
color14		#E6B1B1
color15		#EAD0D0
