# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #DDE8EA
background         #242527
cursor             #DDE8EA

active_tab_foreground     #242527
active_tab_background     #DDE8EA
inactive_tab_foreground   #DDE8EA
inactive_tab_background   #242527

active_border_color   #DDE8EA
inactive_border_color #242527
bell_border_color     #181C25

color0      #4A4B4D
color1		#181C25
color2		#20222B
color3		#504551
color4		#816977
color5		#997B8A
color6		#778E93
color7		#C7D6D9
color8		#8B9698
color9		#202531
color10		#2B2D39
color11		#6B5D6C
color12		#AC8C9F
color13		#CCA4B8
color14		#9FBDC3
color15		#C7D6D9
