# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(1A1B1C)
$foreground = rgb(FDF8F9)
$color0 = rgb(414242)
$color1 = rgb(101516)
$color2 = rgb(4D4F5C)
$color3 = rgb(A46A84)
$color4 = rgb(8E8247)
$color5 = rgb(88AEB8)
$color6 = rgb(BAB0B3)
$color7 = rgb(F3ECEF)
$color8 = rgb(AAA5A7)
$color9 = rgb(161C1E)
$color10 = rgb(66697A)
$color11 = rgb(DB8DB0)
$color12 = rgb(BDAE5F)
$color13 = rgb(B5E8F6)
$color14 = rgb(F8EAEF)
$color15 = rgb(F3ECEF)
