# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(2A2B31)
$foreground = rgb(EDE5F3)
$color0 = rgb(4F5057)
$color1 = rgb(1F223B)
$color2 = rgb(574258)
$color3 = rgb(504E8C)
$color4 = rgb(6C4D62)
$color5 = rgb(A6746E)
$color6 = rgb(9888A6)
$color7 = rgb(DCD2E6)
$color8 = rgb(9A93A1)
$color9 = rgb(292D4E)
$color10 = rgb(755775)
$color11 = rgb(6A68BB)
$color12 = rgb(906783)
$color13 = rgb(DD9A92)
$color14 = rgb(CBB6DD)
$color15 = rgb(DCD2E6)
